### PR TITLE
Usability improvements (callback, options)

### LINKED ISSUE #23: Allow integrations to control redirect
Current implementation for embedded/lightbox options [forces a redirect to occur](https://github.com/globalpayments/rxp-js/blob/master/lib/rxp-hpp.js#L351-L362). Ideally, integrations should be able to control this behavior to adapt to any workflows they deem necessary. This is especially useful in integrations that want to control the experience client-side before passing control to the server-side.

### PR DESCRIPTION
**Pull request by zxfrank**
*Added the ability to handle the answer directly in the page as callback instead of redirecting the viewer to another page.
*Added "autoload" feature so the user do not have to click on a button
*Added options/events to handle iframe resize and or more if needed
*added examples of the above and updated readme

TODO: handle failed attempts directly from modal/embedded instead of redirecting the user each time.

fix #23

### CODE REVIEW

**Comment by cormacmcs** [comment]
This option to handle the answer directly in the page as callback instead of redirecting really needs to be added. Its ridiculous that support for SPA setups isn't supported in 2019.

**Comment by pesimeao** [comment]
What is the current status? Why this wasn't merged yet?

**Comment by marcfielding1** [comment]
@pesimeao Crazy huh? and this is nearly 1 year later.

**Comment by SaiPravesh** [comment]
The callback option must be a feature, this is great work and hope it gets merged soon.

**Pull request closed without merging**
